name: main python
on: 
  push:
    branches:
     - main
  pull_request:
    branches:
     - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4

      - name: Podpiecie Pythona  3.10
        uses: actions/pyhton@v1
        with:
          pyhton-version: '3.10'

      - name: Tworzenie i uruchamianie wirtualnego srodowiska Python
        run: 
          python -m venv venv 
          source venv/bin/activate

      - name: Instalacja depencencji
        run: pip install -r requirements.txt
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
      - name: Akcja Github
        uses: actions/checkout@v4
      - name: Budowoanie aplikacji
        uses: azure/appservice-build@v3
        with: 
          platform: python
          version: 3.10
      - name: Wdrozenie apki do App Service
        uses: azure/webapps-deploy@v2
        with: 
          app-name: 'python123dsa'
          publish-profile: ${{ secrets.AZURE_WEB_PROFILE }}
